
spring:
  application:
    name: api-gateway

  ## Gateway configurations
  cloud:
    gateway:
      routes:
        ## account-service
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account-service/**
          filters:
            - StripPrefix=1

        ## transaction-service
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transaction-service/**
          filters:
            - StripPrefix=1
server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka