
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8072
spring:
  application:
    name: TRANSACTION-SERVICE
  datasource:
    initialization-mode: always
    password: rootroot
    platform: mysql
    url: jdbc:mysql://localhost:3306/transaction_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
    show: true